language: ruby

script: "rake spec"

rvm:
  - 2.0.0

branches:
  only:
    - master

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libpcap-dev xutils-dev -qq
 - gem install bundler

notifications:
  webhooks: http://trema-hubot.herokuapp.com/hubot/travis?room=1
